/// Flutter icons FitnessIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FitnessIcons
///      fonts:
///       - asset: fonts/FitnessIcons.ttf
///
/// 
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class FitnessIcons {
  FitnessIcons._();

  static const _kFontFam = 'FitnessIcons';
  static const _kFontPkg = null;

  static const IconData left_open_big = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_open_big = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_circle = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
